# Generated by Django 2.1.5 on 2019-03-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reltofath', models.CharField(choices=[('B', 'Biological'), ('A', 'Adopted'), ('F', 'Foster'), ('S', 'Sealing')], default='B', max_length=1)),
                ('reltomoth', models.CharField(choices=[('B', 'Biological'), ('A', 'Adopted'), ('F', 'Foster'), ('S', 'Sealing')], default='B', max_length=1)),
                ('childnbrfath', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('childnbrmoth', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_family_changer_related', related_query_name='family_app_familys_changer', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_family_submitter_related', related_query_name='family_app_familys_submitter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('evidence', models.IntegerField(blank=True, null=True)),
                ('_datetime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DateTime')),
                ('_likes', models.ManyToManyField(blank=True, related_name='family_app_marriage_likes_related', related_query_name='family_app_marriages_likes', to=settings.AUTH_USER_MODEL)),
                ('changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_changer_related', related_query_name='family_app_marriages_changer', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_app.Family')),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband_person_seq', to='person_app.Person')),
                ('husbname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='husbname_surname_seq', to='core.SurName')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_submitter_related', related_query_name='family_app_marriages_submitter', to=settings.AUTH_USER_MODEL)),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_person_seq', to='person_app.Person')),
                ('wifename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wifename_surname_seq', to='core.SurName')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_app.Family'),
        ),
        migrations.AddField(
            model_name='child',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_app.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('family', 'person')},
        ),
    ]
