# Generated by Django 2.1.7 on 2019-04-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='child',
            name='family',
        ),
        migrations.RemoveField(
            model_name='child',
            name='person',
        ),
        migrations.AlterField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_husband_related', related_query_name='family_app_marriages_husband', to='person_app.Person'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='husbname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_app_marriage_husbname_related', related_query_name='family_app_marriages_husbname', to='core.SurName'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_wife_related', related_query_name='family_app_marriages_wife', to='person_app.Person'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wifename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_app_marriage_wifename_related', related_query_name='family_app_marriages_wifename', to='core.SurName'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
