# Generated by Django 2.1.7 on 2019-04-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0002_auto_20190404_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriage',
            old_name='family',
            new_name='_family',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='husband',
            new_name='_husband',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='husbname',
            new_name='_husbname',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='wife',
            new_name='_wife',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='wifename',
            new_name='_wifename',
        ),
    ]
