# Generated by Django 2.1.7 on 2019-04-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_auto_20190403_1756'),
        ('family_app', '0003_auto_20190404_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reltofath', models.CharField(choices=[('B', 'Biological'), ('A', 'Adopted'), ('F', 'Foster'), ('S', 'Sealing')], default='B', max_length=1)),
                ('reltomoth', models.CharField(choices=[('B', 'Biological'), ('A', 'Adopted'), ('F', 'Foster'), ('S', 'Sealing')], default='B', max_length=1)),
                ('childnbrfath', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('childnbrmoth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_app_child_family_related', related_query_name='family_app_childs_family', to='family_app.Family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_app_child_person_related', related_query_name='family_app_childs_person', to='person_app.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='marriage',
            name='_husbname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_husbname_related', related_query_name='family_app_marriages_husbname', to='core.SurName'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='_wifename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_wifename_related', related_query_name='family_app_marriages_wifename', to='core.SurName'),
        ),
        migrations.AddField(
            model_name='family',
            name='child',
            field=models.ManyToManyField(through='family_app.Child', to='person_app.Person'),
        ),
    ]
