# Generated by Django 2.1.5 on 2019-04-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_auto_20190403_1756'),
        ('family_app', '0004_auto_20190404_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='person',
        ),
        migrations.AddField(
            model_name='child',
            name='birth',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='family_app_child_person_related', related_query_name='family_app_childs_person', to='person_app.Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='child',
            field=models.ManyToManyField(through='family_app.Child', to='person_app.Birth'),
        ),
    ]
