# Generated by Django 2.2 on 2019-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0007_auto_20190411_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birth',
            new_name='_birth',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='family',
            new_name='_family',
        ),
    ]
