# Generated by Django 2.2 on 2019-04-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0008_auto_20190411_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='childnbrfath',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='childnbrmoth',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
