# Generated by Django 2.2 on 2019-05-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0009_auto_20190428_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_birth_set', related_query_name='childs_birth', to='person_app.Birth'),
        ),
        migrations.AlterField(
            model_name='child',
            name='_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_family_set', related_query_name='childs_family', to='family_app.Family'),
        ),
    ]
