# Generated by Django 2.2 on 2019-05-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0012_auto_20190502_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_family_changer_set', related_query_name='family_app_familys_changer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_family_submitter_set', related_query_name='family_app_familys_submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_changer_set', related_query_name='family_app_marriages_changer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_app_marriage_submitter_set', related_query_name='family_app_marriages_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
