# Generated by Django 2.1.5 on 2019-04-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='person',
            new_name='_person',
        ),
    ]
