# Generated by Django 2.2 on 2019-04-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_auto_20190403_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='birth',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
