# Generated by Django 2.1.5 on 2019-03-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('qualifiers', models.CharField(choices=[('EXC', 'Exactly'), ('ABT', 'About'), ('CAL', 'Calculated'), ('EST', 'Estimated'), ('AFT', 'After'), ('BEF', 'Before'), ('BET', 'Between'), ('FROM', 'Beginning'), ('TO', 'Ending')], default='EXC', max_length=4)),
                ('calendar', models.CharField(choices=[('Gregorian', 'Gregorian'), ('Julian', 'Julian'), ('Hebrew', 'Hebrew'), ('French', 'French'), ('Roman', 'Roman'), ('unknown', 'unknown')], default='Gregorian', max_length=9)),
                ('link', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GivName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('givname', models.CharField(max_length=30, unique=True)),
                ('link', models.PositiveSmallIntegerField(default=0)),
                ('changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_givname_changer_related', related_query_name='core_givnames_changer', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_givname_submitter_related', related_query_name='core_givnames_submitter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('_surname_male', models.CharField(blank=True, max_length=30)),
                ('_surname_female', models.CharField(blank=True, max_length=30)),
                ('link', models.PositiveSmallIntegerField(default=0)),
                ('changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_surname_changer_related', related_query_name='core_surnames_changer', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_surname_submitter_related', related_query_name='core_surnames_submitter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
