# Generated by Django 2.2 on 2019-05-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190428_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givname',
            name='changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_givname_changer_set', related_query_name='core_givnames_changer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='givname',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_givname_submitter_set', related_query_name='core_givnames_submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surname',
            name='changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_surname_changer_set', related_query_name='core_surnames_changer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surname',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_surname_submitter_set', related_query_name='core_surnames_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
